value-en=!English (common)
value-en-GB=English (Traditional)
value-en-US=English (Simplified)
value-en-CA=English (Canadian)
value-zh=Chinese (Simplified)
value-zh-HK=Chinese (Hong Kong)

[view.section-name.key]
context=regular text needs no subkey, but something with a tooltip might want it.\
there are places in the text content that contain numbers in braces, those are parameters.\
the key can be as many levels deep as necessary.

; empty lines and any lines beginning with semicolon will be ignored by the parser.
; context entries are messages from the developer to the translator.
; comment entries are messages from the translator to the developer.
; either one can be marked with a language code, they are only parsed so far as to
; handle multiline values, but don't mean anything to the final application.

comment=a value without a language code is considered default (en) and used as a fallback\
when the desired language has no value.

comment: this is also valid, and considered concatenated to the previous comment after a line break.
comment: colon or equals are both valid.

value=actual text here\
line break {0}

value-zh=ZH:actual text\
{0} in chinese

stale-zh=2023-05-11 10:30:00

comment: stale-markers are there for ease of searching. they don''t need a value,
comment: but should be deleted when the associated language value has been updated.
comment: it will be noted in the debug logs when a stale value has been loaded.

param-0=Double:22

[.tooltip]
comment=use the last fully-qualified key (did not begin with '.') with this appended to it.
comment=so, "view.section-name.key.tooltip"

value=describes the section.key

value-zh=ZH:describes the section.key in chinese

[$rsi-unit]
comment: key for a constant begins with a $.\
that means you don''t have to provide a localization for it, it will forever live on default.\
it can also be referenced by other value=text as {$rsi-unit}.
comment: regular keys can be referenced with {>view.section.key} but cannot contain numbered parameters.

value: m2·K/W

[main.title]
value=Locale''s Test
value-en=EN:Locale
value-en-GB=GB:Locale
value-en-US=US:America
value-zh-hk=HK:Locale

comment=this value has no -zh equivalent. it will be noted in the debug logs when the\
application attempts to access it and falls back to default.


[main.circle-1]
value: circular referencing {>main.circle-2}

[main.circle-2]
value = works because {>main.circle-1}

[main.multiline]
comment: this block demonstrates the difference between multiline and continuation.
value = first part
value: second part_
 third part, all on one line
value-en-CA=line one\
line two\
line three

[main.multiline]
comment: this block overrides the previous one, but only for values that are defined.
value-en-CA=line 1\
line 2\
line 3\
line 4

[main.single-line]
value=line 1 _
still line 1

[format]
value={0:N4}

[.object]
value=ToString() -> {0}

[.named]
value=N{Top:g2}, E{Right:g2}, S{Bottom:g2}, W{Left:g2}

[enum.none]
value=No Selection
[enum.two]
value=Two Selection
[.tooltip]
value=Two With Tooltip
[.desc]
value=Two With Desc