<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\GitDescribe.targets" />

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>PatTech.Localization.Wpf</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageId>PatTech.Localization.WPF</PackageId>
    <AssemblyName>PatTech.Localization.WPF</AssemblyName>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Localization-Core\Localization-Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WordsEdit.Tests" />
  </ItemGroup>
  </Project>
