<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>PatTech.Localization.Wpf</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageId>PatTech.Localization.WPF</PackageId>
    <AssemblyName>PatTech.Localization.WPF</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Localization-Core\Localization-Core.csproj" />
  </ItemGroup>
  </Project>
