<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>true</ImplicitUsings>
    <ApplicationIcon>Resources\words.ico</ApplicationIcon>
    <AssemblyName>Wordsmith</AssemblyName>
  </PropertyGroup>

  
  <ItemGroup>
    <None Update="Resources\*.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" Version="3.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Localization-Core\Localization-Core.csproj" />
    <ProjectReference Include="..\Localization-Wpf\Localization-Wpf.csproj" />
  </ItemGroup>

</Project>
