<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>false</DevelopmentDependency>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>PatTech.Localization.Analyzer</PackageId>
    <PackageVersion>1.0.0.0</PackageVersion>
    <Authors>PatrickZ</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <Title>Words Analyzer</Title>
    <Description>Provides [Localized], and warns when a [Localized] target is given a string that isn't.</Description>
    <PackageTags>localization, analyzers</PackageTags>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
    <AssemblyName>PatTech.Localization</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalizationAnalyzer\LocalizationAnalyzer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="\" />
    <None Update="tools\*.ps1" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\LocalizationAnalyzer.dll" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

</Project>
